//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depo
    {
        public int EsyaId { get; set; }
        public int StokMiktari { get; set; }
    
        public virtual Esya Esya { get; set; }
    }
}
