//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Zimmet = new HashSet<Zimmet>();
        }
    
        public int kullaniciId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public int DepartmanId { get; set; }
        public int RutbeId { get; set; }
        public string kullaniciAdi { get; set; }
        public string sifre { get; set; }
        public int Aktiflik { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual Rutbe Rutbe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zimmet> Zimmet { get; set; }
    }
}
