//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YazilimSinamaProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zimmet
    {
        public int CalisanId { get; set; }
        public int EsyaId { get; set; }
        public System.DateTime ZimmetVakti { get; set; }
        public int ZimmetId { get; set; }
    
        public virtual Esya Esya { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
